# Generated by Django 2.0.6 on 2018-06-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180621_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_score', models.PositiveIntegerField(verbose_name='语文成绩')),
                ('math_score', models.PositiveIntegerField(verbose_name='数学成绩')),
                ('english_score', models.PositiveIntegerField(verbose_name='英语成绩')),
                ('student_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Stu', verbose_name='学生姓名')),
            ],
            options={
                'verbose_name': '成绩管理',
                'verbose_name_plural': '成绩管理',
            },
        ),
    ]
