# Generated by Django 2.0.5 on 2018-09-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('age', models.IntegerField(verbose_name='学生年龄')),
                ('classes', models.CharField(choices=[('1', '初一'), ('2', '初二'), ('3', '初三')], default='1', max_length=30)),
            ],
            options={
                'verbose_name': '学生列表',
                'verbose_name_plural': '学生列表',
            },
        ),
    ]
