# Generated by Django 2.0.5 on 2018-09-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=20, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='students',
            name='classes',
            field=models.CharField(choices=[('1', '初一'), ('2', '初二'), ('3', '初三')], default='1', max_length=30, verbose_name='年级'),
        ),
    ]
